version: '3.7'

services:
  guacozy:
    build:
      context: ./guacozy/
    restart: always
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY=abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
      - FIELD_ENCRYPTION_KEY=qjq4ObsXMqiqQyfKgD-jjEGm4ep8RaHKGRg4ohGCi1A=
      - DB_ENGINE=django.db.backends.mysql'
      - DB_NAME=pingpong_db
      - DB_USER=pingpong_db_user
      - DB_PASSWORD=pingpong_db_password
      - DB_HOST=mysql
      - DB_PORT=3306
      - DJANGO_ALLOWED_HOSTS=*
    ports:
      - 8000:8000
      - 10443:443
    depends_on:
      - "guacd"
      -  "db"
  
  guacd:
    image: guacamole/guacd:latest
    hostname: guacd
    environment:
      - GUACD_LOG_LEVEL=debug
    ports:
      - 4822:4822
      
  db:
    image: mysql:5.7
    restart: always
    hostname: mysql
    environment:
      MYSQL_DATABASE: 'pingpong_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'pingpong_db_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'pingpong_db_password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'pingpong_db_root_password'
      useSSL: 'false'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    command: --init-file /data/application/initdb.sql
    volumes:
      - ./initdb.sql:/data/application/initdb.sql
      - pingpong_db:/var/lib/mysql

# Names our volume
volumes:
  pingpong_db:
  static_volume:
  media_volume:
  certificates:

