# Generated by Django 3.1.4 on 2022-02-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220226_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Instructor'), (3, 'Counsellor')], default=1),
        ),
    ]
