# Generated by Django 3.1.4 on 2022-02-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20220227_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
