# Generated by Django 3.1.4 on 2022-02-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_lesson_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='handson_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
